
name: Lint & Test

on:
  pull_request:
    branches: [ main ]
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: 1.8.2
    - name: Install dependencies
      run: poetry install --all-extras
    - name: Lint
      run: poetry run ruff check .
    - name: Check formatting
      run: poetry run ruff format --check .
    - name: Type checking
      run: poetry run mypy .
    - name: Run Azurite
      shell: bash
      run: |
        npm install -g azurite
        azurite --blobHost 127.0.0.1 --blobPort 10000 &
    - name: Run tests
      run: |
        poetry run pytest --cov blobby --cov-report term-missing --cov-report xml
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
